# ✅ SPA(Single Page Application) 설정: 모든 경로를 index.html로 리디렉트
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ✅ 일반 서버리스 함수 설정 (Netlify Functions)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" # 최신 ESBuild 사용

# ✅ Edge Functions 설정
[[edge_functions]]
  path = "/api/getCardSummary"  # ✅ URL 경로 수정
  function = "getCardSummary"

# ✅ 일반 서버리스 함수 개별 설정 (Netlify Functions)
[[functions]]
  name = "getCardKingdomPrice"
  path = "/api/getCardKingdomPrice"  # ✅ URL 경로 수정
