[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[functions]]
  path = "/.netlify/functions/getCardKingdomPrice"
  function = "getCardKingdomPrice"

[[edge_functions]]
  path = "/.netlify/edge-functions/getCardSummary"
  function = "getCardSummary"
