# ✅ SPA(Single Page Application) 설정: 모든 경로를 index.html로 리디렉트
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ✅ Netlify 일반 Functions 설정 (서버리스 함수)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" # 최신 ESBuild 사용

# ✅ 개별 함수 설정 (각 서버리스 함수에 대한 설정)
[functions.getCardKingdomPrice]
  path = "/api/getCardKingdomPrice"

# ✅ Edge Functions 설정 (스트리밍을 위한 Edge 환경)
[[edge_functions]]
  path = "/api/getCardSummary"
  function = "getCardSummary"
