# SPA(Single Page Application) 설정: 모든 경로를 index.html로 리디렉트
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Netlify 일반 Functions 설정 (서버리스 함수)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" # 최신 ESBuild 사용
  external_node_modules = ["@sparticuz/chromium", "puppeteer-core"]

# Edge Functions 설정 (스트리밍을 위한 Edge 환경)
[[edge_functions]]
  path = "/api/getCardSummary"
  function = "getCardSummary"

# CardKingdom 가격 제공
[build]
"""
node netlify/functions/updateIdentifiers.mjs && node netlify/functions/updatePrices.mjs && npm run build
"""