name: Update card prices (daily)

on:
  push:
  schedule:
    # 매일 04:00(KST) ≒ 19:00(UTC)
    - cron:  '0 19 * * *'
  workflow_dispatch:

jobs:
  prices:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Download AllPrices.json.gz
        run: |
          mkdir -p data
          curl -L https://mtgjson.com/api/v5/AllPrices.json.gz -o data/AllPrices.json.gz

      - name: Parse uuid → price map
        run: |
          python scripts/ck_retail.py \
            data/AllPrices.json.gz \
            data/ck_retail.csv \
            --csv

      - name: Get latest scry2uuid map
        uses: actions/download-artifact@v4
        with:
          name: scry2uuid
          path: data

      - name: Join & build final CSV
        run: |
          python scripts/merge_prices.py \
            data/ck_retail.csv \
            data/scry2uuid.json \
            data/price_records.csv

      - name: Upsert into Neon
        env:
          DATABASE_URL: ${{ secrets.NETLIFY_DATABASE_URL }}
        run: |
          python scripts/upsert_prices.py data/price_records.csv